services:
  versionvault:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: versionvault
    ports:
      - "2080:80"
    environment:
      - WUD_API_URL=http://your-wud-server:3000/api/containers
    networks:
      - proxy
    volumes:
      - nginx_logs:/var/log/nginx
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.versionvault.entrypoints=http
      - traefik.http.routers.versionvault.rule=Host(`your-domain.example.com`)
      - traefik.http.middlewares.versionvault-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.versionvault.middlewares=versionvault-https-redirect
      - traefik.http.routers.versionvault-secure.entrypoints=https
      - traefik.http.routers.versionvault-secure.rule=Host(`your-domain.example.com`)
      - traefik.http.routers.versionvault-secure.tls=true
      - traefik.http.routers.versionvault-secure.tls.certresolver=cloudflare
      - traefik.http.routers.versionvault-secure.service=versionvault
      - traefik.http.services.versionvault.loadbalancer.server.port=80
volumes:
  nginx_logs:

networks:
  proxy:
    external: true
